### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by sameerhoda** [ranjanrak/OptionChainStream#1]
Hi Ranjan, was excited to see this amazing peice of work and thank you for this

unfortunately have not been able to get the pip install to work and i get the following error

can you please correct this or set me in the right direction.

$ pip install optionchain_stream

Collecting optionchain_stream
  Using cached optionchain_stream-0.2-py3-none-any.whl (8.2 kB)
ERROR: Requested optionchain_stream from https://files.pythonhosted.org/packages/e1/a9/c7da09471a507817f35fc06f182279f4bddaaf849a36e90d182b97c290d8/optionchain_stream-0.2-py3-none-any.whl#sha256=77a959ba13ac972a2a88969597cf36cf61f7df7c3ed27b2d4d5c9241ea7fd187 has different version in metadata: '0.1'

**Comment by Jaimin7632** [comment]
For now, you can clone this code to your working dir and after that you have to install Redis manually. `pip install redis` `apt install redis-server`

**Comment by ranjanrak** [comment]
@sameerhoda 
This is fixed in [new version](https://pypi.org/project/optionchain-stream/)(which introduces additional field IV).
