### ISSUE TITLE
reuse kite instance

### ISSUE THREAD

**Issue by singla96** [ranjanrak/OptionChainStream#3]
Is there a way as of now to reuse kite session(created outside this package) instead of passing api_key and generating and new session

**Comment by ranjanrak** [comment]
@singla96 
Maybe you can consider directly assigning **access_token** from the current active session to [KiteTicker](https://github.com/ranjanrak/OptionChainStream/blob/8e647b84f485492cf45150d3651d216ad0462528/optionchain_stream/websocket.py#L20) and [Kite connect](https://github.com/ranjanrak/OptionChainStream/blob/8e647b84f485492cf45150d3651d216ad0462528/optionchain_stream/websocket.py#L27) instance.

**Comment by sriraj1122** [comment]
@ranjanrak  Yes we are doing the same.  Instead of passing request_token we modified it to accept access_token so that we don't need to generate new session everytime we use this.

**Comment by ranjanrak** [comment]
@singla96 @sriraj1122 
Have added this feature to reuse the previous active session's access_token. You can read more about the [usage here](https://github.com/ranjanrak/OptionChainStream#usage). You can upgrade to the latest version by: `pip install optionchain_stream --upgrade`
