### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by sriraj1122** [ranjanrak/OptionChainStream#4]
I installed OptionChainStream package and executed below code.

from optionchain_stream import OptionChain
# OptionStream = OptionChain("api_key", "secret_key", "request_token",
#                     "option_symbol", "option_expiry_date in yyyy-mm-dd format")
# Eg: OptionChain('XXXXXX', 'XXXXXXX', 'XXXXXX', 
 #                                'ONGC', '2021-02-25')
OptionStream = OptionChain("xxx", "xxx", "xxx",
                    'ONGC', '2021-5-27')

# Sync master instrument data to DB(redis)     
# This sync is required only once daily at initial run             
OptionStream.sync_instruments()

# Stream option chain data in real-time
StreamData = OptionStream.create_option_chain()

print(StreamData)
for data in StreamData:
    print(data)

I am getting below error.  Can you please help.

TypeError: cannot pickle '_thread.lock' object

**Comment by ranjanrak** [comment]
Hey @sriraj1122 @bivinbenny 
Thanks for pointing out the thread handling issue. It's fixed and the package is updated. You can upgrade to the latest version by:
`pip install optionchain_stream --upgrade`

**Comment by sriraj1122** [comment]
Thanks so much @ranjanrak   Appreciate your prompt response.  This is a great module to get Option Chain with ease.
